//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCamDo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extend
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public int Times { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
